### ISSUE TITLE
start-notebook isn't there anymore

### ISSUE THREAD

**Issue by UnkindPartition** [cdiener/qiime-docker#1]
Thanks for the image. However, while trying to build it, I got:

```
Step 28 : ADD https://raw.githubusercontent.com/jupyter/docker-stacks/master/minimal-notebook/start-notebook.sh /usr/local/bin/
Got HTTP status code >= 400: 404 Not Found
```

**Comment by cdiener** [comment]
Thanks for the report! Will look into it (hope I'll manage today).

**Comment by cdiener** [comment]
Should be fixed now. Still testing the dada2 branch but master is fine. Sorry for the delay.
